name: |
  Push Version Tags
description: |
  Pushes supplementary (major, minor) version tags to a repository. It is useful for creating tags for major and minor versions based on a base version.
  For example, if the base version is `v1.2.3`, it will create tags `v1` and `v1.2`.

branding:
  icon: "tag"
  color: "gray-dark"

inputs:
  github_token:
    description: |
      Github token used for API calls. Required scope - 'contents: write'
    default: ${{ github.token }}

  owner:
    description: |
      Owner of the repository
    default: ${{ github.repository_owner }}

  repo:
    description: |
      Repository name
    default: ${{ github.event.repository.name }}

  version:
    description: |
      Base version to be used for tags. Should be in format {major}.{minor}.{patch} or v{major}.{minor}.{patch} (e.g. 1.2.3 or v1.2.3)
    required: true

  major:
    description: |
      Weather to push major version tag
    default: "true"

  minor:
    description: |
      Weather to push minor version tag
    default: "true"

outputs:
  major_version:
    description: |
      Major version tag
    value: ${{ steps.prepare-versions.outputs.major_version }}

  minor_version:
    description: |
      Minor version tag
    value: ${{ steps.prepare-versions.outputs.minor_version }}

runs:
  using: "composite"
  steps:
    - name: Validate version format
      shell: bash
      run: |
        # Validate version format
        if [[ ! ${{ inputs.version }} =~ ^v?.+\..+\..+$ ]]; then
          echo "Invalid version format."
          echo "Should be in format {major}.{minor}.{patch} or v{major}.{minor}.{patch} (e.g. 1.2.3 or v1.2.3)"
          exit 1
        fi

    - name: Prepare versions
      id: prepare-versions
      shell: bash
      run: |
        # Prepare versions
        major=$(echo ${{ inputs.version }} | cut -d. -f1)
        minor=$(echo ${{ inputs.version }} | cut -d. -f2)
        patch=$(echo ${{ inputs.version }} | cut -d. -f3)

        major_version="${major}"
        echo "major_version=${major_version}" >> $GITHUB_OUTPUT

        minor_version="${major}.${minor}"
        echo "minor_version=${minor_version}" >> $GITHUB_OUTPUT

    - name: Get tag info
      id: get-tag-info
      uses: ovsds/get-tag-info-action@v1
      with:
        github_token: ${{ inputs.github_token }}
        owner: ${{ inputs.owner }}
        repo: ${{ inputs.repo }}
        tag_name: ${{ inputs.version }}

    - name: Create or update major tag
      id: create-or-update-major-tag
      if: ${{ inputs.major == 'true' }}
      uses: ovsds/create-or-update-ref-action@v1
      with:
        github_token: ${{ inputs.github_token }}
        owner: ${{ inputs.owner }}
        repo: ${{ inputs.repo }}
        ref: "tags/${{ steps.prepare-versions.outputs.major_version }}"
        sha: ${{ steps.get-tag-info.outputs.commit_sha }}

    - name: Create or update minor tag
      id: create-or-update-minor-tag
      if: ${{ inputs.minor == 'true' }}
      uses: ovsds/create-or-update-ref-action@v1
      with:
        github_token: ${{ inputs.github_token }}
        owner: ${{ inputs.owner }}
        repo: ${{ inputs.repo }}
        ref: "tags/${{ steps.prepare-versions.outputs.minor_version }}"
        sha: ${{ steps.get-tag-info.outputs.commit_sha }}
