name: Create Reference
description: Create a reference in the repository

inputs:
  ref:
    description: "The reference to create"
    required: true
  sha:
    description: "The SHA of the commit to reference"
    required: true
  github_token:
    description: "GitHub token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Create reference
      shell: bash
      run: |
        # Create the reference
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/git/refs \
          -F ref=refs/${{ inputs.ref }} \
          -F sha=${{ inputs.sha }}
      env:
        GH_TOKEN: ${{ inputs.github_token }}
