name: Update Reference
description: Update a reference in the repository

inputs:
  ref:
    description: "The reference to update"
    required: true
  sha:
    description: "The SHA of the commit to reference"
    required: true
  github_token:
    description: "GitHub token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Update reference
      shell: bash
      run: |
        # Update the reference
        gh api \
        --method PATCH \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        /repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/git/refs/${{ inputs.ref }} \
        -F sha=${{ inputs.sha }}
      env:
        GH_TOKEN: ${{ inputs.github_token }}
