name: Delete Reference
description: Delete a reference from the repository

inputs:
  owner:
    description: "Owner of the repository"
    required: true
    default: ${{ github.repository_owner }}
  repo:
    description: "Repository name"
    required: true
    default: ${{ github.event.repository.name }}
  ref:
    description: "The reference to delete"
    required: true
  github_token:
    description: "GitHub token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Delete reference
      shell: bash
      run: |
        # Delete the reference
        gh api \
          --method DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${OWNER}/${REPO}/git/refs/${REF}
      env:
        OWNER: ${{ inputs.owner }}
        REPO: ${{ inputs.repo }}
        REF: ${{ inputs.ref }}
        GH_TOKEN: ${{ inputs.github_token }}
