name: Push version tags

on:
  release:
    types: [published]

jobs:
  push-version-tags:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push Version Tags
        uses: ./
        with:
          version: ${{ github.event.release.tag_name }}
